export const FETCH_BASKET_REQUEST='FETCH_BASKET_REQUEST'
export const FETCH_BASKET_SUCCESS='FETCH_BASKET_SUCCESS'
export const FETCH_BASKET_FAIL='FETCH_BASKET_FAIL'
export const ADD_TO_BASKET_SUCCESS='ADD_TO_BASKET_SUCCESS'