export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL'


export const PRODUCT_IMAGE_REQUEST='PRODUCT_IMAGE_REQUEST'
export const PRODUCT_IMAGE_SUCCESS='PRODUCT_IMAGE_SUCCESS'
export const PRODUCT_IMAGE_FAIL='PRODUCT_IMAGE_FAIL'

export const PRODUCT_IMAGE_DETAIL_REQUEST='PRODUCT_IMAGE_DETAIL_REQUEST'
export const PRODUCT_IMAGE_DETAIL_SUCCESS='PRODUCT_IMAGE_DETAIL_SUCCESS'
export const PRODUCT_IMAGE_DETAIL_FAIL='PRODUCT_IMAGE_DETAIL_FAIL'

export const PRODUCT_STOCK_REQUEST='PRODUCT_STOCK_REQUEST'
export const PRODUCT_STOCK_SUCCESS='PRODUCT_STOCK_SUCCESS'
export const PRODUCT_STOCK_FAIL='PRODUCT_STOCK_FAIL'